spring.application.name=admin-service
server.port=8086

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/neobank

# Feign clients URLs
user-service.url=http://localhost:8081
card-service.url=http://localhost:8083
transaction-service.url=http://localhost:8084